import express from "express";
import ProductController from "../controller/product.controller.js";
import authMiddleware from "../middleware/auth.middleware.js";
import upload from "../middleware/multer.middleware.js";
const routerAPI = express.Router();
routerAPI.get("/", ProductController.getProduct);
routerAPI.get("/all", ProductController.getAllProducts);
routerAPI.get("/top-10-best-selling", ProductController.getTop10BestSellingProducts);
routerAPI.get("/top-10-best-viewing", ProductController.getTop10BestViewProducts);
routerAPI.post("/", authMiddleware, upload.array("images", 10), ProductController.createProduct);
routerAPI.get("/productWithoutPromotion", ProductController.findProductsWithoutPromotion);
routerAPI.get("/:id", ProductController.getProductById);
routerAPI.put("/:id", authMiddleware, upload.array("images", 10), ProductController.updateProduct);
routerAPI.delete("/:id", authMiddleware, ProductController.deleteProduct);
routerAPI.get("/similar/:id", ProductController.getSimilarProducts);
export default routerAPI;
